# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qr < Formula
  desc "A lightweight QR encoder"
  homepage "https://github.com/chey/qr"
  version "0.1.1"

  on_macos do
    url "https://github.com/chey/qr/releases/download/v0.1.1/qr_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "8b21e0babdb23dbc70ef9be33815a7a2f72ff1bbbcd6bcd6aa727da4cbddd44a"

    def install
      bin.install "qr"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Qr
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chey/qr/releases/download/v0.1.1/qr_0.1.1_Linux_x86_64.tar.gz"
      sha256 "f5f4b1b51a44721efcb52191d5beec5941079bf826ae767614b84bff0bd539c6"

      def install
        bin.install "qr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chey/qr/releases/download/v0.1.1/qr_0.1.1_Linux_armv6.tar.gz"
      sha256 "c8c2dbd0128115b9c0b7885307f21d5f235c33d0ed3256dfd60821afeba51ed7"

      def install
        bin.install "qr"
      end
    end
  end
end
