# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qr < Formula
  desc "A lightweight QR encoder"
  homepage "https://github.com/chey/qr"
  version "0.1.1"

  on_macos do
    url "https://github.com/chey/qr/releases/download/v0.1.1/qr_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "17853a04770034d00563924be8a14a0593900d266db9091f3bf6bd0d6bbf56f1"

    def install
      bin.install "qr"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Qr
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chey/qr/releases/download/v0.1.1/qr_0.1.1_Linux_armv6.tar.gz"
      sha256 "7a107ae7e233492c53e281517ca6091b49ff89b351c0f2d6e658f16f02ce557b"

      def install
        bin.install "qr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chey/qr/releases/download/v0.1.1/qr_0.1.1_Linux_x86_64.tar.gz"
      sha256 "f236ace591bb5bd5922bc21064ff43bc2348ab2d1b7bd90ba2b75d28bc9d0095"

      def install
        bin.install "qr"
      end
    end
  end
end
