# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qr < Formula
  desc "A lightweight QR encoder"
  homepage "https://github.com/chey/qr"
  version "0.1.1"

  on_macos do
    url "https://github.com/chey/qr/releases/download/v0.1.1/qr_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "b1de9234a1244b98ee7ec4dde990f0b7b5cee945fd7247a36f8280af2fd8123e"

    def install
      bin.install "qr"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Qr
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/chey/qr/releases/download/v0.1.1/qr_0.1.1_Linux_armv6.tar.gz"
      sha256 "72f6999e0c7304fddcb47098acb7dc3d54c05dcffb36d3ec23fe7eeea82f9e9f"

      def install
        bin.install "qr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chey/qr/releases/download/v0.1.1/qr_0.1.1_Linux_x86_64.tar.gz"
      sha256 "4ea7bbe22f84cd6ff6ba609fb51e376e034a97b6bd2d176dd4914c7bfda7847b"

      def install
        bin.install "qr"
      end
    end
  end
end
